// PARCHE ANTI-CRASH OBLIGATORIO
const { Client } = require('discord.js-selfbot-v13');
const ClientUserSettingManager = require('discord.js-selfbot-v13/src/managers/ClientUserSettingManager.js');
const originalPatch = ClientUserSettingManager.prototype._patch;
ClientUserSettingManager.prototype._patch = function (data) {
    if (data && !data.friend_source_flags) {
        data.friend_source_flags = { all: false, mutual_friends: false, mutual_guilds: false };
    }
    return originalPatch.call(this, data);
};

const express = require('express');
const app = express();
app.get('/', (req, res) => res.send('⚔️ MOTOR DE ASEDIO V26 - MAYÚSCULAS Y VELOCIDAD ⚔️'));
app.listen(process.env.PORT || 8080);

// --- CONFIGURACIÓN DE IDs ---
const OBJETIVOS = ["1457984414121459856", "1447142638326120458", "1479755930483691610", "1479748142722191514", "1457144912561832182"];
const PRIORITARIOS = ["1369181247896817685", "1369174478596345897", "1369174476574687243"];
const CANALES_RANDOM = ["1239719951435304960"];

// --- BARDEOS EN MAYÚSCULAS ---
const MIS_MENSAJES = [
    ".T CPUTIÑAGACHATUBER MAMITA CEJOTORRA QUIERES PENE SHAM4? NALGARERA GAMAMITA PUTA DE FRANKITA Y DE NEG4 SHE",
    ".T CEJOTIÑAANDGAMAMI BRAZOS MÁS LONJUDOS MEJICHANGA NALGA MONCLOVEÑA SOY TU MASHO/TÍO DE 40 AÑOS",
    ".T CEJOTIÑAGOLPEADA MALDITA Q QUIERE EDITAR SUS NALG4S DESDE GROK CUANDO SU BRAZO LONJUDO ANDA FILTRADO POR LA MALDITA DE ERRE ELA EN IG Y HAY CAPS Q TENGO YO Q SON IRREFUTABLES DE ESTO🤣🤣🤣",
    ".T CJOTORRA MAMELE MÁS MEJICHANGA Q A SIMIAS COMO A TU LAS DEBEN DE LLEVAR AL MATADERO POR MEJICANAS GÜEY",
    ".T LORDA Y MIENTRAS TANTO CJOTORRA VIENDO TODO CON SU CARA DE INDIA MEJICANA TENIENDO Q MANTENER A SU MAMITA Y COMO JOTIÑA ES PUTA PUES ES UNA FRIJOPERRA JAJAJA, JAJSJAJSJAJSA PERRA DE LOS CERROS DE MICHOACAN, SIEMPRE SERÁS UNA MAMITA BIEN NERVIOSA Q HASTA NEGA LA TIENE DE PUTITA EN MD CHE, Y Q BUENO PORQUE BÁSICAMENTE NEGA ES MI MAMÁ Y TÚ LO SABES PERR4, Q BUENO Q ESA DIOSA TE TENGA DE ZORRA Y TE ANDE ARRASTRANDOTE A LOS CONDES DE CHILE, MEJOR DICHO DE MI CHILE PORQUE TU ANDAS ENCIMA DE CHILE Q PARA ADENTRO DE TUS NALGORRAS Q ANDAN DESESPERADISIMAS PORQUE LILIZ/MALAYA(EXP DE INQUISIDOR) TE ANDE LLENANDO DE MECOS Y CHORREANDO DE SEM3N TUS NALGAS APESTOSAS Q EXPELEN A PEDITOS DE MICHOACAN, ESOS PEDITOS DE MILF DE MÁS DE 20 AÑOS CHE JAJSAJSJSKAJS🇨🇱💨🍑🇨🇱💨🍑🇨🇱🍑🇨🇱💨🍑💨🤣💨🤣🍑🇨🇱🍑💨💨🍑 P3RR4 ADIESTRADA, POR CADA Q TE PELEES CON NEGA YO VOY A ANDAR APOYANDO A NEGA AUNQUE ESTE DISTANCIADA DE MI AUNQUE BÁSICAMENTE PUEDO DECIR Q ELLA ES TU DOMADORA DE CHILE CHE, TE PARA DEDEANDO EL PEDORRRILLO Y EVIDENCIAS HAY, NADIE TE VA A TOMAR ENSERIÓ IGUALMENTE SI TODO LO Q DICES LO HACES TREMENDO MEME PERRITA ARRASTRADA POR LILIZ!!!!! 🤣🤣🤣🤣🤣 SENDO PEDORRAZO Q LLEVAS HIJA DE SU CHINGADA MADRE",
    ".T FRIJOLERA FRIJOLERA DILE DOMADORA A TU M4CH4 Q TE TIENE DE PUTITA Q SOLO GENERAS Q SE BURLEN DE TU NALGA ALABANDO A UNA Q TE TRAICIONA LA NALGA🤣🤣🤣, Y PUES MIRA PERRA YO ME VOY A BURLAR DE TI EN ESTE MENSAJE PORQUE MIRA MAMITA CJOTORRA, PODEMOS DECIR Q ERES UNA NALGA MUY MAYORA DE 20 AÑOS DELATADA POR SUS MACHAS DE MEMEDROID (APP DONDE TE CREES DIOSA) PERRO HASTA ELLAS TE DESVIRG4R0N PORQUE PODEMOS DECIR Q ELLAS FUERON LAS PRIMERAS EN DELATARTE Y COMERTE EL ANO CRUJIENTE Q EXPELE Y ANDA SACANDO PEDOS DE LAS N4LG4S CHE, PODEMOS SEGUIR DICIENDO Q ERES UNA PERR4 BIEN MARRANA Q LA CONSIDERAN FRIJOLERA HASTA A LA Q LLAMA DIOSA COMO GAMAMITA CHE ES Q PERRA TU ERES BIEN DWNIGRABLE, TODAS SE RÍEN DE TI, TE TRAICIONA GAMAMITA Y TE USA💀💀💀💀, POBRE TORPEDORROTE TE PODEMOS DECIR NOPALERA, FRIJOLERA, MEJICHANGA HORRENDA CON VOZ AGUDA Y ENCIMA UNA CHANGA DE 1.60 SHE🤣🤣🤣🤣🤣 ENCIMA PIENSAS Q YO ME TOMO ENSERIÓ TUS NALGAS CUANDO LO ÚNICO Q LE HAGO A TUS NALGAS ES BURLARME DE TI CERDA Q TRAGA PURO FRÍJOL CON HUEVOTES DE SU TORO, TE PARAS TRAGAMDO MIS HUEBOS CH CJOTORRA, POBRE MAMITA, TODAS TE DESVIRGAN EL AN0 Y TE QUIEREN HACER SU PUTITA PESE A Q ESTAS MÁS LESIONADA Q CUALQUIER COSA.... 😈😈😈😈🇨🇱💨🍑🇲🇽",
    ".T JOAN MACH4 G4M4MITA DIRÍA LA PUTITA MARRONA Y CONCHUDA DE CEJUDA JAJJAJAA",
    ".T CHICHUDA VENGAN MEJICHANGAS DENLE TET4 A SU MACHETE JSJAJAJA",
    ".T CJOTANGAANDGAMAMI CEJOTORRA Y GAMAMITA SON TAXISTAS Y ENCIMA TIENEN 20-18 AÑOS Y SU CARA ESTA MÁS DESFIGURADA Y CON LA MENSTRUACIÓN DE LA ABUELA DE CEJOTIÑA 🤣🤣🤣🤣",
    ".T CEJUDA2 PINCHE PERRA CJOTIÑA SOS UN KAGU3 DE RISA SHE NI QUIEN TE TOME ENSERIÓ PENDEJITA SI DESDE Q ESTAS TRAICIONADA TODOS TE HAN VENIDO TOMANDO LA COLA PARA TRAICIONARTE Y OLERTE EL PEDORRO CHE, SI HASTA AJENAS A LA CJ TE QUIEREN OLER EL QLO, HASTA LA MULTICUENTRA TRAVESTI DE HADESA Q ES REDBLACKA TE JODE LAS NALGAS🤣🤣🤣, YA NI HABLAR Q LESBERY TE ARDIÓ EL CULETE POR MICHOACANA 😈😈😈",
    ".T NITO PERRA TIENES Q ENTENDER Q SOS MEXINDIA DE MICHOACAN Y ERES CHATARRERA/TAXISTA😈😈😈🫵🫵🫵🤣🤣😂😂😂",
    ".T INDIA LA MEJINDIA DE MICHOACAN TRAICIONADA POR PABLA VERACRUZANA DE POZA RICA (HUNDIDA) Y POR GAMAMITA OTRA VEZ JDKDJJSJS, PORQUE HASTA EL INDIO DE PABLA FUE A ROMPERTE LA NALGAS ENTRE DICIEMBRE Y FEBRERO Y TE PUSO TODAS LAS NALGAS GORDAS EN RIDÍCULO COMO YA ES COSTUMBRE SHE, ME DA RISA Q ESE INDIO TE DEJO BIEN EYACULADOT4 A HASTA PODRÍA DECIR Q EL INDIO DE PABLA SIENDO HORRIBLE FUE CAPAZ DE ESTRESARTE EL CULITO POR HORAS Y POR MÁS Q ESE INDIO SER LENTO FUE CAPAZ DE ROMPERTE LAS NALGAS POR CHANGA BISEXUAL, HABLANDO DE BISEXUAL TAMBIÉN HAY Q DECIR Q ERES UNA FRIJOLERA Q SE ARDIÓ CON EL EDUARDO PORQUE EL EDUARDO LE ARDIÓ EL CUL0 CHE, PORQUE TUS NALGAS DE MEJICANOTA TUVIERON Q COMPARTIR CUENTA CON LA BISEXUAL CHILENA DE ZATHORNA PARA CUMPLIR SU DESEO DE SER MUJER ANTE GD, GD Q LAS LLENO DE MECOS A AMBAS PEDORRONAS Q ESTÁN FURIOSAS Y CELOSAS PORQUE SU TÍO EL DESVIRGADOR DE USTEDAS NO SE ARDE Y NO SE ESTRESADA A DIFEEJCIADE CJOTORRA Q CON EL MÁS MÍNIMO ROSON DE VERG4 YA SE ANDA ARDIENDO Y COMO TUS NLAGA SOS CHANGA PIENSAS Q YO ME TOMO ENSERIÓ SUS TETAS DE 20 AÑOS CUANDO CLARAMENTE SOLO ME BURLO DE USTED PORQUE ERES FRACASADA Y DAS RISA CHANGA, DAS RISA PUEBLERINA DE SIERRA PUTA SIN ACCESO AL MAR Y ENCIMA ES MARRONA PORQUE ERES MARRONA EN IG Y ERES UNA MORENA CHAPARRA🤣🤣💨🇲🇽🇨🇱🍑🇨🇱🍑🇨🇱💨🍑💨 MUCHO FRIJOL TE SACAS DE LAS NALGAS AMIGA PERRA JODIDA POR SU MACHA GAMAMITA 🍑🇨🇱🇨🇱💨🇲🇽🍑🤣🤣🍑🍑🇲🇽🤣💨🤣🍑🇲🇽🍑🇲🇽🤣🍑🤣🍑🤣🍑🤣🍑🇲🇽🍑🇲🇽🍑🇲🇽🍑🇲🇽🍑🇲🇽🍑🇲🇽🤣🍑",
    ".T INSANA TE ARDIÓ LAS NALGAS INSANA LA MISMA ARJENCHANGA Q FILTRO A LORDA Y CEJOTIÑA JAJAJA, MIRA CEJOTIÑA Q DECIR DE TI LA VERDAD, SI NADIE SE TOMA ENSERIÓ TUS NALGORRAS ES PORQUE CUALQUIERA TE TIENE DE PERRA CHE, RECUERDO Q HASTA UNA PROSTITUTA TE CALLO LAS NALGAS Y ASI TE QUIERES PONER DELANTE DE TUS MACHOS MAYORES (TIPO WARSZLA) Q CLARAMENTE TE PARAN ABUSANDO, NI Q DECIR Q ERES LA MAMÁ DEL MANJUNTER/JS/SPIDERMAN TE DESPLOMA EL CULO🤣🤣🤣🤣🤣🤣, NO PERRA TU SI ESTAS BIEN JODIDA CHE, TENES 20 AÑOS, ESTAS DESEMPLEADA, SE PUEDE DECIR Q ERES UN PEDON BISEXUAL Y TRAVESTI Q LE ENCANTA FINGIR SER MUJER Y SE ENAMORO DE GD Y FUE LLENADA DE MECOS DE LA WARSZLIZA Y Q LE LLEVA CASI 6 AÑOS A MANHUTER PERRA PEDOFILA!!! MALDITA PEDOFILA CHE, ESTAS BIEN JODIDA Y ACABADA CJOTORRONGA 🤣🤣",
    ".T CPUTIÑA CHINGERO DE SEMEN EN SUS ANOS DE FRACASADAS PE JSJSJS",
    ".T KAYADA JDKDJDJJSS LORDA PUTITA SE CALLO EN SPAM HACE 1H EN COAHUILA JAJAJDJJSHDW Y ESTO VA A SEGUIR SHE JAKSJDJJDJDJDDK",
    ".T CJOTORR4 VAGINA DE CEJOTIÑA SHE JDJSKDJKSJSKSJD",
    ".T NALGOTANGA APURATE NALGOTANGA SALVA A GAMAMITA Q SE MURIÓ JAJAJAJA",
    ".T CEJUD4 SE LE DESCONFIGURO LA NALGA A CHATARRERA GAMAMITA JAJAJAJAJAJAJAJAJAJAJA"
];

const MSJ_LARGO = `.T CEJOTIÑAANDGAMAMI \n<@1425209744603218020> <@1195495311045558272> <@1369070242684473485> <@984956970014486528> <@1072352198836621385> CULOMBIANO ARGENCHANGAS <@1435003733393281055> <@1400251089361567885> <@1429177016703516764> DANIELA <@1438314463970328578> <@1384045898958508085> <@1446586105553227807> <@1452154841676775567> <@957014429822750771> <@1423439348430405722> <@1455444386421674007> <@765971830442819674> <@1394021604127936772> <@1452533908699611236> <@1438662990021922869> <@1459077041637953651> <@1468117706099396816> <@1467397075204309034> <@1466878653932634195> <@1458314974794616902> <@1403986874153832550> <@1470913175401533543> <@1464354934785839155> <@1394023020896714762> <@1399500980889976902> <@1470230646529069086> <@1462897561894649876> @everyone DANIELA <@1386330375952793723> <@1399500980889976902> <@1466878653932634195> \nhttps://files.catbox.moe/d0wcx2.mp4`;

function aplicarBypass(msg) {
    const hex = Math.random().toString(16).substring(2, 8).toUpperCase();
    return `${msg} **[#${hex}]**`;
}

function crearBot(token, nombre, delayInic) {
    const client = new Client({ checkUpdate: false });
    let indexObj = 0;

    // ATAQUE PRIORITARIOS (8-13 SEG)
    async function attack() {
        try {
            const target = OBJETIVOS[indexObj];
            indexObj = (indexObj + 1) % OBJETIVOS.length;
            const chanID = PRIORITARIOS[Math.floor(Math.random() * PRIORITARIOS.length)];
            const channel = await client.channels.fetch(chanID).catch(() => null);
            if (channel) {
                const bardeo = MIS_MENSAJES[Math.floor(Math.random() * MIS_MENSAJES.length)];
                await channel.send(aplicarBypass(`${bardeo} <@${target}>`));
            }
        } catch (e) {}
        setTimeout(attack, Math.floor(Math.random() * 5000) + 8000);
    }

    // ATAQUE RANDOM (CADA 2 MINS)
    async function attackRandom() {
        try {
            const channel = await client.channels.fetch(CANALES_RANDOM[0]).catch(() => null);
            if (channel) {
                await channel.send(aplicarBypass(MSJ_LARGO));
            }
        } catch (e) {}
        setTimeout(attackRandom, 120000);
    }

    // AUTO-RESPUESTA (SI ELLAS HABLAN EN OTRO LADO)
    client.on('messageCreate', async (msg) => {
        if (msg.author.bot) return;
        if (OBJETIVOS.includes(msg.author.id)) {
            if (!PRIORITARIOS.includes(msg.channel.id) && !CANALES_RANDOM.includes(msg.channel.id)) {
                try {
                    const bardeo = MIS_MENSAJES[Math.floor(Math.random() * MIS_MENSAJES.length)];
                    await msg.channel.send(aplicarBypass(`${bardeo} <@${msg.author.id}>`));
                } catch (e) {}
            }
        }
    });

    client.on('ready', () => {
        console.log(`⚔️ ${nombre} EN POSICIÓN`);
        setTimeout(attack, delayInic);
        setTimeout(attackRandom, delayInic + 10000);
    });
    client.login(token).catch(() => {});
}

const tokens = [process.env.TOKEN_1, process.env.TOKEN_2, process.env.TOKEN_3, process.env.TOKEN_4, process.env.TOKEN_5, process.env.TOKEN_6];
tokens.forEach((t, i) => { if (t) crearBot(t, `BOT_${i+1}`, i * 3000); });
// PARCHE ANTI-CRASH OBLIGATORIO
const { Client } = require('discord.js-selfbot-v13');
const ClientUserSettingManager = require('discord.js-selfbot-v13/src/managers/ClientUserSettingManager.js');
const originalPatch = ClientUserSettingManager.prototype._patch;
ClientUserSettingManager.prototype._patch = function (data) {
    if (data && !data.friend_source_flags) {
        data.friend_source_flags = { all: false, mutual_friends: false, mutual_guilds: false };
    }
    return originalPatch.call(this, data);
};

const express = require('express');
const app = express();
app.get('/', (req, res) => res.send('⚔️ MOTOR DE ASEDIO V26 - MAYÚSCULAS Y VELOCIDAD ⚔️'));
app.listen(process.env.PORT || 8080);

// --- CONFIGURACIÓN DE IDs ---
const OBJETIVOS = ["1457984414121459856", "1447142638326120458", "1479755930483691610", "1479748142722191514", "1457144912561832182"];
const PRIORITARIOS = ["1369181247896817685", "1369174478596345897", "1369174476574687243"];
const CANALES_RANDOM = ["1239719951435304960"];

// --- BARDEOS EN MAYÚSCULAS ---
const MIS_MENSAJES = [
    ".T CPUTIÑAGACHATUBER MAMITA CEJOTORRA QUIERES PENE SHAM4? NALGARERA GAMAMITA PUTA DE FRANKITA Y DE NEG4 SHE",
    ".T CEJOTIÑAANDGAMAMI BRAZOS MÁS LONJUDOS MEJICHANGA NALGA MONCLOVEÑA SOY TU MASHO/TÍO DE 40 AÑOS",
    ".T CEJOTIÑAGOLPEADA MALDITA Q QUIERE EDITAR SUS NALG4S DESDE GROK CUANDO SU BRAZO LONJUDO ANDA FILTRADO POR LA MALDITA DE ERRE ELA EN IG Y HAY CAPS Q TENGO YO Q SON IRREFUTABLES DE ESTO🤣🤣🤣",
    ".T CJOTORRA MAMELE MÁS MEJICHANGA Q A SIMIAS COMO A TU LAS DEBEN DE LLEVAR AL MATADERO POR MEJICANAS GÜEY",
    ".T LORDA Y MIENTRAS TANTO CJOTORRA VIENDO TODO CON SU CARA DE INDIA MEJICANA TENIENDO Q MANTENER A SU MAMITA Y COMO JOTIÑA ES PUTA PUES ES UNA FRIJOPERRA JAJAJA, JAJSJAJSJAJSA PERRA DE LOS CERROS DE MICHOACAN, SIEMPRE SERÁS UNA MAMITA BIEN NERVIOSA Q HASTA NEGA LA TIENE DE PUTITA EN MD CHE, Y Q BUENO PORQUE BÁSICAMENTE NEGA ES MI MAMÁ Y TÚ LO SABES PERR4, Q BUENO Q ESA DIOSA TE TENGA DE ZORRA Y TE ANDE ARRASTRANDOTE A LOS CONDES DE CHILE, MEJOR DICHO DE MI CHILE PORQUE TU ANDAS ENCIMA DE CHILE Q PARA ADENTRO DE TUS NALGORRAS Q ANDAN DESESPERADISIMAS PORQUE LILIZ/MALAYA(EXP DE INQUISIDOR) TE ANDE LLENANDO DE MECOS Y CHORREANDO DE SEM3N TUS NALGAS APESTOSAS Q EXPELEN A PEDITOS DE MICHOACAN, ESOS PEDITOS DE MILF DE MÁS DE 20 AÑOS CHE JAJSAJSJSKAJS🇨🇱💨🍑🇨🇱💨🍑🇨🇱🍑🇨🇱💨🍑💨🤣💨🤣🍑🇨🇱🍑💨💨🍑 P3RR4 ADIESTRADA, POR CADA Q TE PELEES CON NEGA YO VOY A ANDAR APOYANDO A NEGA AUNQUE ESTE DISTANCIADA DE MI AUNQUE BÁSICAMENTE PUEDO DECIR Q ELLA ES TU DOMADORA DE CHILE CHE, TE PARA DEDEANDO EL PEDORRRILLO Y EVIDENCIAS HAY, NADIE TE VA A TOMAR ENSERIÓ IGUALMENTE SI TODO LO Q DICES LO HACES TREMENDO MEME PERRITA ARRASTRADA POR LILIZ!!!!! 🤣🤣🤣🤣🤣 SENDO PEDORRAZO Q LLEVAS HIJA DE SU CHINGADA MADRE",
    ".T FRIJOLERA FRIJOLERA DILE DOMADORA A TU M4CH4 Q TE TIENE DE PUTITA Q SOLO GENERAS Q SE BURLEN DE TU NALGA ALABANDO A UNA Q TE TRAICIONA LA NALGA🤣🤣🤣, Y PUES MIRA PERRA YO ME VOY A BURLAR DE TI EN ESTE MENSAJE PORQUE MIRA MAMITA CJOTORRA, PODEMOS DECIR Q ERES UNA NALGA MUY MAYORA DE 20 AÑOS DELATADA POR SUS MACHAS DE MEMEDROID (APP DONDE TE CREES DIOSA) PERRO HASTA ELLAS TE DESVIRG4R0N PORQUE PODEMOS DECIR Q ELLAS FUERON LAS PRIMERAS EN DELATARTE Y COMERTE EL ANO CRUJIENTE Q EXPELE Y ANDA SACANDO PEDOS DE LAS N4LG4S CHE, PODEMOS SEGUIR DICIENDO Q ERES UNA PERR4 BIEN MARRANA Q LA CONSIDERAN FRIJOLERA HASTA A LA Q LLAMA DIOSA COMO GAMAMITA CHE ES Q PERRA TU ERES BIEN DWNIGRABLE, TODAS SE RÍEN DE TI, TE TRAICIONA GAMAMITA Y TE USA💀💀💀💀, POBRE TORPEDORROTE TE PODEMOS DECIR NOPALERA, FRIJOLERA, MEJICHANGA HORRENDA CON VOZ AGUDA Y ENCIMA UNA CHANGA DE 1.60 SHE🤣🤣🤣🤣🤣 ENCIMA PIENSAS Q YO ME TOMO ENSERIÓ TUS NALGAS CUANDO LO ÚNICO Q LE HAGO A TUS NALGAS ES BURLARME DE TI CERDA Q TRAGA PURO FRÍJOL CON HUEVOTES DE SU TORO, TE PARAS TRAGAMDO MIS HUEBOS CH CJOTORRA, POBRE MAMITA, TODAS TE DESVIRGAN EL AN0 Y TE QUIEREN HACER SU PUTITA PESE A Q ESTAS MÁS LESIONADA Q CUALQUIER COSA.... 😈😈😈😈🇨🇱💨🍑🇲🇽",
    ".T JOAN MACH4 G4M4MITA DIRÍA LA PUTITA MARRONA Y CONCHUDA DE CEJUDA JAJJAJAA",
    ".T CHICHUDA VENGAN MEJICHANGAS DENLE TET4 A SU MACHETE JSJAJAJA",
    ".T CJOTANGAANDGAMAMI CEJOTORRA Y GAMAMITA SON TAXISTAS Y ENCIMA TIENEN 20-18 AÑOS Y SU CARA ESTA MÁS DESFIGURADA Y CON LA MENSTRUACIÓN DE LA ABUELA DE CEJOTIÑA 🤣🤣🤣🤣",
    ".T CEJUDA2 PINCHE PERRA CJOTIÑA SOS UN KAGU3 DE RISA SHE NI QUIEN TE TOME ENSERIÓ PENDEJITA SI DESDE Q ESTAS TRAICIONADA TODOS TE HAN VENIDO TOMANDO LA COLA PARA TRAICIONARTE Y OLERTE EL PEDORRO CHE, SI HASTA AJENAS A LA CJ TE QUIEREN OLER EL QLO, HASTA LA MULTICUENTRA TRAVESTI DE HADESA Q ES REDBLACKA TE JODE LAS NALGAS🤣🤣🤣, YA NI HABLAR Q LESBERY TE ARDIÓ EL CULETE POR MICHOACANA 😈😈😈",
    ".T NITO PERRA TIENES Q ENTENDER Q SOS MEXINDIA DE MICHOACAN Y ERES CHATARRERA/TAXISTA😈😈😈🫵🫵🫵🤣🤣😂😂😂",
    ".T INDIA LA MEJINDIA DE MICHOACAN TRAICIONADA POR PABLA VERACRUZANA DE POZA RICA (HUNDIDA) Y POR GAMAMITA OTRA VEZ JDKDJJSJS, PORQUE HASTA EL INDIO DE PABLA FUE A ROMPERTE LA NALGAS ENTRE DICIEMBRE Y FEBRERO Y TE PUSO TODAS LAS NALGAS GORDAS EN RIDÍCULO COMO YA ES COSTUMBRE SHE, ME DA RISA Q ESE INDIO TE DEJO BIEN EYACULADOT4 A HASTA PODRÍA DECIR Q EL INDIO DE PABLA SIENDO HORRIBLE FUE CAPAZ DE ESTRESARTE EL CULITO POR HORAS Y POR MÁS Q ESE INDIO SER LENTO FUE CAPAZ DE ROMPERTE LAS NALGAS POR CHANGA BISEXUAL, HABLANDO DE BISEXUAL TAMBIÉN HAY Q DECIR Q ERES UNA FRIJOLERA Q SE ARDIÓ CON EL EDUARDO PORQUE EL EDUARDO LE ARDIÓ EL CUL0 CHE, PORQUE TUS NALGAS DE MEJICANOTA TUVIERON Q COMPARTIR CUENTA CON LA BISEXUAL CHILENA DE ZATHORNA PARA CUMPLIR SU DESEO DE SER MUJER ANTE GD, GD Q LAS LLENO DE MECOS A AMBAS PEDORRONAS Q ESTÁN FURIOSAS Y CELOSAS PORQUE SU TÍO EL DESVIRGADOR DE USTEDAS NO SE ARDE Y NO SE ESTRESADA A DIFEEJCIADE CJOTORRA Q CON EL MÁS MÍNIMO ROSON DE VERG4 YA SE ANDA ARDIENDO Y COMO TUS NLAGA SOS CHANGA PIENSAS Q YO ME TOMO ENSERIÓ SUS TETAS DE 20 AÑOS CUANDO CLARAMENTE SOLO ME BURLO DE USTED PORQUE ERES FRACASADA Y DAS RISA CHANGA, DAS RISA PUEBLERINA DE SIERRA PUTA SIN ACCESO AL MAR Y ENCIMA ES MARRONA PORQUE ERES MARRONA EN IG Y ERES UNA MORENA CHAPARRA🤣🤣💨🇲🇽🇨🇱🍑🇨🇱🍑🇨🇱💨🍑💨 MUCHO FRIJOL TE SACAS DE LAS NALGAS AMIGA PERRA JODIDA POR SU MACHA GAMAMITA 🍑🇨🇱🇨🇱💨🇲🇽🍑🤣🤣🍑🍑🇲🇽🤣💨🤣🍑🇲🇽🍑🇲🇽🤣🍑🤣🍑🤣🍑🤣🍑🇲🇽🍑🇲🇽🍑🇲🇽🍑🇲🇽🍑🇲🇽🍑🇲🇽🤣🍑",
    ".T INSANA TE ARDIÓ LAS NALGAS INSANA LA MISMA ARJENCHANGA Q FILTRO A LORDA Y CEJOTIÑA JAJAJA, MIRA CEJOTIÑA Q DECIR DE TI LA VERDAD, SI NADIE SE TOMA ENSERIÓ TUS NALGORRAS ES PORQUE CUALQUIERA TE TIENE DE PERRA CHE, RECUERDO Q HASTA UNA PROSTITUTA TE CALLO LAS NALGAS Y ASI TE QUIERES PONER DELANTE DE TUS MACHOS MAYORES (TIPO WARSZLA) Q CLARAMENTE TE PARAN ABUSANDO, NI Q DECIR Q ERES LA MAMÁ DEL MANJUNTER/JS/SPIDERMAN TE DESPLOMA EL CULO🤣🤣🤣🤣🤣🤣, NO PERRA TU SI ESTAS BIEN JODIDA CHE, TENES 20 AÑOS, ESTAS DESEMPLEADA, SE PUEDE DECIR Q ERES UN PEDON BISEXUAL Y TRAVESTI Q LE ENCANTA FINGIR SER MUJER Y SE ENAMORO DE GD Y FUE LLENADA DE MECOS DE LA WARSZLIZA Y Q LE LLEVA CASI 6 AÑOS A MANHUTER PERRA PEDOFILA!!! MALDITA PEDOFILA CHE, ESTAS BIEN JODIDA Y ACABADA CJOTORRONGA 🤣🤣",
    ".T CPUTIÑA CHINGERO DE SEMEN EN SUS ANOS DE FRACASADAS PE JSJSJS",
    ".T KAYADA JDKDJDJJSS LORDA PUTITA SE CALLO EN SPAM HACE 1H EN COAHUILA JAJAJDJJSHDW Y ESTO VA A SEGUIR SHE JAKSJDJJDJDJDDK",
    ".T CJOTORR4 VAGINA DE CEJOTIÑA SHE JDJSKDJKSJSKSJD",
    ".T NALGOTANGA APURATE NALGOTANGA SALVA A GAMAMITA Q SE MURIÓ JAJAJAJA",
    ".T CEJUD4 SE LE DESCONFIGURO LA NALGA A CHATARRERA GAMAMITA JAJAJAJAJAJAJAJAJAJAJA"
];

const MSJ_LARGO = `.T CEJOTIÑAANDGAMAMI \n<@1425209744603218020> <@1195495311045558272> <@1369070242684473485> <@984956970014486528> <@1072352198836621385> CULOMBIANO ARGENCHANGAS <@1435003733393281055> <@1400251089361567885> <@1429177016703516764> DANIELA <@1438314463970328578> <@1384045898958508085> <@1446586105553227807> <@1452154841676775567> <@957014429822750771> <@1423439348430405722> <@1455444386421674007> <@765971830442819674> <@1394021604127936772> <@1452533908699611236> <@1438662990021922869> <@1459077041637953651> <@1468117706099396816> <@1467397075204309034> <@1466878653932634195> <@1458314974794616902> <@1403986874153832550> <@1470913175401533543> <@1464354934785839155> <@1394023020896714762> <@1399500980889976902> <@1470230646529069086> <@1462897561894649876> @everyone DANIELA <@1386330375952793723> <@1399500980889976902> <@1466878653932634195> \nhttps://files.catbox.moe/d0wcx2.mp4`;

function aplicarBypass(msg) {
    const hex = Math.random().toString(16).substring(2, 8).toUpperCase();
    return `${msg} **[#${hex}]**`;
}

function crearBot(token, nombre, delayInic) {
    const client = new Client({ checkUpdate: false });
    let indexObj = 0;

    // ATAQUE PRIORITARIOS (8-13 SEG)
    async function attack() {
        try {
            const target = OBJETIVOS[indexObj];
            indexObj = (indexObj + 1) % OBJETIVOS.length;
            const chanID = PRIORITARIOS[Math.floor(Math.random() * PRIORITARIOS.length)];
            const channel = await client.channels.fetch(chanID).catch(() => null);
            if (channel) {
                const bardeo = MIS_MENSAJES[Math.floor(Math.random() * MIS_MENSAJES.length)];
                await channel.send(aplicarBypass(`${bardeo} <@${target}>`));
            }
        } catch (e) {}
        setTimeout(attack, Math.floor(Math.random() * 5000) + 8000);
    }

    // ATAQUE RANDOM (CADA 2 MINS)
    async function attackRandom() {
        try {
            const channel = await client.channels.fetch(CANALES_RANDOM[0]).catch(() => null);
            if (channel) {
                await channel.send(aplicarBypass(MSJ_LARGO));
            }
        } catch (e) {}
        setTimeout(attackRandom, 120000);
    }

    // AUTO-RESPUESTA (SI ELLAS HABLAN EN OTRO LADO)
    client.on('messageCreate', async (msg) => {
        if (msg.author.bot) return;
        if (OBJETIVOS.includes(msg.author.id)) {
            if (!PRIORITARIOS.includes(msg.channel.id) && !CANALES_RANDOM.includes(msg.channel.id)) {
                try {
                    const bardeo = MIS_MENSAJES[Math.floor(Math.random() * MIS_MENSAJES.length)];
                    await msg.channel.send(aplicarBypass(`${bardeo} <@${msg.author.id}>`));
                } catch (e) {}
            }
        }
    });

    client.on('ready', () => {
        console.log(`⚔️ ${nombre} EN POSICIÓN`);
        setTimeout(attack, delayInic);
        setTimeout(attackRandom, delayInic + 10000);
    });
    client.login(token).catch(() => {});
}

const tokens = [process.env.TOKEN_1, process.env.TOKEN_2, process.env.TOKEN_3, process.env.TOKEN_4, process.env.TOKEN_5, process.env.TOKEN_6];
tokens.forEach((t, i) => { if (t) crearBot(t, `BOT_${i+1}`, i * 3000); });
    client.on('ready', () => {
        console.log(`✅ ${nombre} ACTIVO`);
        setTimeout(attack, delayInicial);
        setTimeout(attackRandom, delayInicial + 10000);
    });
    client.login(token).catch(() => {});
}

const tokens = [process.env.TOKEN_1, process.env.TOKEN_2, process.env.TOKEN_3, process.env.TOKEN_4, process.env.TOKEN_5, process.env.TOKEN_6];
tokens.forEach((t, i) => { if (t) crearBot(t, `BOT_${i+1}`, i * 30000); });
